source "https://rubygems.org"

gem "byebug"

# Data driven
gem "csv"

# download file
gem "uuid", "~> 2.3", ">= 2.3.8"
gem "fileutils", "~> 0.7.2"

# download with browser
gem "rest-client", "~> 1.8"

group :test do
  gem "selenium-webdriver"
end
